import { redirect } from "next/navigation";
import { completeOnboardingAction } from "@/actions/saas-project.actions";
import { OnboardingWizard } from "@/components/onboarding/onboarding-wizard";
import { getActiveProject } from "@/lib/project";
import { PageHeader } from "@/components/ui";
import { DemoBanner } from "@/components/ui/demo-badge";

export const metadata = { title: "Set up your SaaS · Launchpad Catalyst" };

export default async function OnboardingPage({
  searchParams,
}: {
  searchParams: Promise<Record<string, string | string[] | undefined>>;
}) {
  const params = await searchParams;
  const isNew = params.new === "1";

  const project = await getActiveProject();
  if (project?.onboardingComplete && !isNew) redirect("/dashboard");

  return (
    <>
      <PageHeader
        title="Tell us what you're building"
        description="You don't need to know your audience or keywords. Catalyst will figure that out."
      />
      <DemoBanner>
        Your analysis will be generated by the built-in demo engine and matched
        against bundled demo conversations. No AI key or platform connection is
        configured yet.
      </DemoBanner>
      <OnboardingWizard action={completeOnboardingAction} mode={isNew ? "new" : "edit"} />
    </>
  );
}
