import { redirect } from "next/navigation";
import { completeOnboardingAction } from "@/actions/saas-project.actions";
import { OnboardingWizard } from "@/components/onboarding/onboarding-wizard";
import { getActiveProject } from "@/lib/project";
import { PageHeader } from "@/components/ui";
import { DemoBanner } from "@/components/ui/demo-badge";

export const metadata = { title: "Set up your SaaS · Launchpad Catalyst" };

export default async function OnboardingPage() {
  const project = await getActiveProject();
  if (project?.onboardingComplete) redirect("/dashboard");

  return (
    <>
      <PageHeader
        title="Tell us about your SaaS"
        description="This drives everything else: who to target, where they are, and which conversations are worth your time."
      />
      <DemoBanner>
        Your analysis will be generated by the built-in demo engine and matched
        against bundled demo conversations. No AI key or platform connection is
        configured yet.
      </DemoBanner>
      <OnboardingWizard action={completeOnboardingAction} />
    </>
  );
}
